In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.0.0


In [3]:
mnist = tf.keras.datasets.mnist

In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [5]:
x_train, x_test = x_train / 254.0  ,  x_test / 254.0

In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

In [7]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 8s 127us/sample - loss: 0.0867 - accuracy: 0.9739
Epoch 2/5
60000/60000 [==============================] - 8s 127us/sample - loss: 0.0732 - accuracy: 0.9767
Epoch 3/5
60000/60000 [==============================] - 8s 137us/sample - loss: 0.0646 - accuracy: 0.9796
Epoch 4/5
60000/60000 [==============================] - 8s 135us/sample - loss: 0.0575 - accuracy: 0.9816
Epoch 5/5
60000/60000 [==============================] - 8s 140us/sample - loss: 0.0516 - accuracy: 0.9829


In [11]:
evaluation = model.evaluate(x_test,  y_test, verbose=2)

10000/1 - 0s - loss: 0.0394 - accuracy: 0.9800


In [12]:
print(evaluation[0])   #test loss
print(evaluation[1])   #test accuracy

0.06937677921280265
0.98


In [13]:
import matplotlib.pyplot as plt
plt.imshow(x_test[90],cmap='Greys')
model.predict_classes(x_test[90].reshape(1,28, 28 ))

array([3], dtype=int64)

In [14]:
model.predict_classes(x_test[7].reshape(1,28,28))

array([9], dtype=int64)

In [15]:
y_test[7]

9

In [16]:
import keras
keras.__version__

Using TensorFlow backend.


'2.2.4'

In [17]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [18]:
train_images.shape

(60000, 28, 28)

In [19]:

len(train_labels)

60000

In [20]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [21]:
test_images.shape

(10000, 28, 28)

In [22]:
len(test_labels)

10000

In [10]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [11]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28,28)))
network.add(layers.Dense(10, activation='softmax'))

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

In [61]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

NameError: name 'network' is not defined

In [48]:
from keras import models
from keras import layers
model = models.Sequential()
model.add(layers.Dense(32, activation='relu', input_shape=(784,)))
model.add(layers.Dense(10, activation='softmax'))

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

In [ ]:
input_tensor = layers.Input(shape=(784,))
x = layers.Dense(32, activation='relu')(input_tensor)
output_tensor = layers.Dense(10, activation='softmax')(x)
model = models.Model(inputs=input_tensor, outputs=output_tensor)

In [50]:
from keras import optimizers
model.compile(optimizer=optimizers.RMSprop(lr=0.001),
loss='mse',
metrics=['accuracy'])

ValueError: ('Could not interpret optimizer identifier:', <keras.optimizers.RMSprop object at 0x000002465825C588>)

In [ ]:
model.fit(input_tensor, target_tensor, batch_size=128, epochs=10)

In [49]:
from keras.datasets import imdb
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(
num_words=10000)

Exception: URL fetch failure on https://s3.amazonaws.com/text-datasets/imdb.npz: None -- [Errno 11001] getaddrinfo failed